#!/bin/sh
# Copyright(c) 2011-2013 Shenzhen TP-LINK Technologies Co.Ltd.
# file     usbuser
# brief    
# author   Zhu Xianfeng<zhuxianfeng@tp-link.net>
# version  1.0.0
# date     29Apr14
# history  arg 1.0.0, 29Apr14, Zhu Xianfeng, Create the file. 

. /lib/functions.sh

if [ $# -ne 3 ]; then
    return
fi

local username=$1
local password=$2
local account_type=$3

local auth="$(uci_get usbshare.global.auth_all)"
local oldusername="$(uci_get usbshare.account.username)"
local oldusername1="$(uci_get usbshare.account1.username)"
local oldpassword="$(uci_get usbshare.account.password)"
local oldpassword1="$(uci_get usbshare.account1.password)"
echo " oldusername: $oldusername\n oldpassword: $oldpassword\n oldusername1: $oldusername1\n oldpassword1: $oldpassword1\n" > /dev/console

local smbconf="/etc/samba/smb.conf.template"

escaped_str() {
    local word=$1

    word=${word//\\/\\\\}
    echo "${word}"
}

password=$(escaped_str "$password")

# smbpasswd
if [ ! -e /etc/samba/smbpasswd ]; then
    touch /etc/samba/smbpasswd
fi
echo "# admin = alias" > /etc/samba/smbusers
echo "" > /etc/samba/lognames.deny

#account_type = 0 : administration
#               1 : user
if [ $account_type -eq 0 ]; then
    ##ftp
    echo -e $password'\n'$password'\n' | passwd admin 1>/dev/null 2>&1
    ftp_alias stop "$oldusername" admin
    if [ "$username" != "admin" -a "$auth" = "on" ];then
        ftp_alias start "$username" admin
    fi

    ##smbusers && smbpasswd
    echo -e $password'\n'$password'\n' | smbpasswd -s -a admin 1>/dev/console 2>&1
    if [ "$username" != "admin" -a "$oldusername1" != "guest" ]; then
        echo -e "admin = $username" > /etc/samba/smbusers
        echo -e "guest = $oldusername1" >> /etc/samba/smbusers
        echo -e "admin guest" > /etc/samba/lognames.deny
    elif [ "$username" != "admin" ]; then
        echo -e "admin = $username" > /etc/samba/smbusers
        echo -e "admin" > /etc/samba/lognames.deny
    elif [ "$oldusername1" != "guest" ]; then
        echo -e "guest = $oldusername1" > /etc/samba/smbusers
        echo -e "guest" > /etc/samba/lognames.deny
    fi
else
    ##ftp
    if [ "$auth" = "on" ];then
        echo -e $password'\n'$password'\n' | passwd guest 1>/dev/null 2>&1
    fi
    ftp_alias stop "$oldusername1" guest
    if [ "$auth" = "off" ];then
        ftp_alias start anonymous guest
    fi
    if [ "$username" != "guest" -a "$auth" = "on" ];then
        ftp_alias start "$username" guest
    fi

    ##smbusers && smbpasswd
    if [ "$auth" = "on" ];then
        sed -i 's/^.*map to guest = Bad User$/\#map to guest = Bad User/g' $smbconf
        echo -e $password'\n'$password'\n' | smbpasswd -s -a guest 1>/dev/console 2>&1
    fi
    if [ "$oldusername" != "admin" -a "$username" != "guest" ]; then
        echo -e "admin = $oldusername" > /etc/samba/smbusers
        echo -e "guest = $username" >> /etc/samba/smbusers
        echo -e "admin guest" > /etc/samba/lognames.deny
    elif [ "$username" != "guest" ]; then
        echo -e "guest = $username" > /etc/samba/smbusers
        echo -e "guest" > /etc/samba/lognames.deny
    elif [ "$oldusername" != "admin" ]; then
        echo -e "admin = $oldusername" > /etc/samba/smbusers
        echo -e "admin" > /etc/samba/lognames.deny
    fi
fi

if [ $account_type -eq 0 -a "$username" != "$oldusername" ]; then
    /etc/init.d/afpd stop
    /etc/init.d/avahi-daemon stop

    /usr/sbin/tm_checkrun $username
fi
