#!/bin/sh
. /lib/functions.sh

SYS_SET_TIME=$(uci_get_state systime core sync)
config_load /etc/config/system
config_get type ntp type

[ "$type" = "auto" -a $SYS_SET_TIME -eq 1 ] && {
	auto_update_support=$(uci get profile.@firmware_upgrade[0].auto_update_support -c "/etc/profile.d" -q)
	if [ "$auto_update_support" = "yes" ];then
		[ ! -f "/tmp/auto_update_lock.lua" ] && reboot
	else
		reboot
	fi
}
