#!/bin/sh

[ "$DEVICE" = "lo" -o "$INTERFACE" = "wanv6" ] && exit 0

. /lib/functions.sh

local enable
config_load amazon_ffs
config_get enable "ffs" "enable" "off"

[ "$ACTION" = "ifup" -a "$enable" = "on" ] && {
    . /lib/ffs/ffs_core.sh

    if [ "$INTERFACE" = "wifi" ]; then
        # ffs interface, update speed rule 
        ffs_rule_exit
        ffs_rule_init
    else
        # other interface, do ip conflict check
        local ret=$(ffs_network_ip_is_conflict $INTERFACE)

        [ "$ret" = "true" ] && {
            /etc/init.d/ffs restart
        }
    fi
}

