#!/bin/sh

# start wps pbc
if [ "$(nvram kget btntestflag)" == "1" -a "$(uci get factory.factorymode.enable)" != "yes" ]; then
	lua -e "require 'luci.controller.admin.wireless'.wireless_wps_connect({option = 'connect'})"
else
	if [ ! -e /tmp/btn_check ];then
		echo 0 > /tmp/btn_check
	fi
	ret=$(cat /tmp/btn_check)
	ret=$(($ret | 0x8))
	echo $ret > /tmp/btn_check
fi