#!/bin/sh

if [ "$(nvram kget rftestflag)" == "1" ]; then
	rmmod wl
	rmmod dhd
	rmmod igs
	rmmod emf
	rmmod hnd

	# kill acsd2, it may change the channel or stop TX.
	# delete pid file of acsd2 at /tmp/dm/ first, or debug_monitor will start acsd2
	acsd_pid=`pgrep acsd2|awk -F " " '{print $1}'`
	rm -rf /tmp/dm/${acsd_pid}
	killall acsd2

	nvram kset rftestflag=0
	mv /tp_data/radio_bk /tmp/radio_bk_tmp
	wifi start
	mv /tmp/radio_bk_tmp /tp_data/radio_bk
fi