#!/bin/sh

# Copyright (C) 2009 OpenWrt.org

# echo ACTION=$ACTION, DEVPATH=$DEVPATH, SUBSYSTEM=$SUBSYSTEM, BUSNUM=$BUSNUM >/dev/console

# echo "--------------" >>/dev/console
#echo "busnum=$BUSNUM" >> /dev/console
#echo "action=$ACTION" >> /dev/console
#echo "intf=$INTERFACE" >> /dev/console
#echo "devnum=$DEVNUM" >> /dev/console
#echo "dev=$DEVICE" >> /dev/console
#echo "pdt=$PRODUCT" >> /dev/console
#echo "type=$TYPE" >> /dev/console
#echo "--------------" >>/dev/console

#ignore usb hub event
HUBFLAG=`echo $DEVPATH | cut -d "-" -f 3 | cut -d ":" -f 1`
if [ $HUBFLAG = "0" ]; then 
	return
fi
PORTNUM=`echo $DEVPATH | cut -d "-" -f 2 | cut -d "/" -f 3`
echo $DEVPATH >> /dev/console
# plug in USB2.0 Device generates port3 event, plug in USB3.0 Device generates port4 event
echo "USB port event happened -- port=$PORTNUM" >> /dev/console
case "$PORTNUM" in
    5|6)
        USB="USB2"
        ;;
    *)
        exit 0
        ;;
esac

case "$ACTION" in
	add)
		# update LEDs
        ledcli ${USB}_twinkle
		;;
	remove)
		# update LEDs
        uci set ledctrl.$USB.ledon='0'
        ledcli $USB
		;;
esac	
		


		
